server:
  port: 8801

spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/englishSpeakingDB
    username: sauravS
    password: saurav@simmi

  jpa:
    hibernate:
      ddl-auto: update
    database: MYSQL

#interakt:
#  apiKey: key
#  apiSecret: password


